name: cuda_test
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip
  - pip:
    - sphinx>=7.0.0
    - sphinx-rtd-theme>=1.3.0
    - sphinx-autobuild>=2021.3.14
  - cudatoolkit
  - cudnn
  - pytorch
  - torchvision
  - torchaudio 